cabal-version: 3.4
name: modifier-macros
version: 0.1.0.0
build-type: Simple
category: Generics
synopsis: Derive monoids using GHC field modifiers
description: Please see the README on GitHub at <https://github.com/konn/modifier-macros#readme>
license: BSD-3-Clause
license-file: LICENSE
author: Hiromi ISHII
maintainer: konn.jinro_at_gmail.com
copyright: "2026 (c) Hiromi ISHII"
extra-doc-files:
  CHANGELOG.md
  README.md

bug-reports: https://github.com/konn/modifier-macros/issues
homepage: https://github.com/konn/modifier-macros#readme

source-repository head
  type: git
  location: https://github.com/konn/modifier-macros.git
  subdir: modifier-macros

common defaults
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wmissing-export-lists
    -Wmissing-home-modules
    -Wpartial-fields
    -Wredundant-constraints
    -Wunused-packages

  default-language: GHC2024
  build-depends: base >=4.18 && <5

library
  import: defaults
  build-depends:
    generic-lens,
    ghc ==10.0.0.20260917,
    lens,

  hs-source-dirs: src
  -- cabal-gild: discover src --exclude=src/**/Internal.hs
  exposed-modules:
    Data.Monoid.Deriving.Modifiers
    Data.Monoid.Deriving.Modifiers.Types

  -- cabal-gild: discover src --include=src/**/Internal.hs
  other-modules:

executable modifier-macros-exe
  import: defaults
  main-is: Main.hs
  -- cabal-gild: discover app --exclude=app/Main.hs
  other-modules:
  hs-source-dirs: app
  ghc-options:
    -threaded
    -rtsopts
    -with-rtsopts=-N

  build-depends: modifier-macros

test-suite modifier-macros-test
  import: defaults
  type: exitcode-stdio-1.0
  hs-source-dirs: test
  main-is: Main.hs
  ghc-options:
    -threaded
    -rtsopts
    -O2
    -with-rtsopts=-N

  -- cabal-gild: discover test --exclude=test/Main.hs
  other-modules: Data.Monoid.Deriving.ModifiersSpec
  build-depends:
    modifier-macros,
    tasty,
    tasty-hunit,

  build-tool-depends: tasty-discover:tasty-discover
